// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: improbable/spatialos/playerauth/v2/playerauth.proto

#include "improbable/spatialos/playerauth/v2/playerauth.pb.h"
#include "improbable/spatialos/playerauth/v2/playerauth.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace improbable {
namespace spatialos {
namespace playerauth {
namespace v2 {

static const char* PlayerAuthService_method_names[] = {
  "/improbable.spatialos.playerauth.v2.PlayerAuthService/CreateLoginToken",
  "/improbable.spatialos.playerauth.v2.PlayerAuthService/CreatePlayerIdentityToken",
  "/improbable.spatialos.playerauth.v2.PlayerAuthService/DecodePlayerIdentityToken",
  "/improbable.spatialos.playerauth.v2.PlayerAuthService/CreateDevelopmentAuthenticationToken",
  "/improbable.spatialos.playerauth.v2.PlayerAuthService/GetDevelopmentAuthenticationToken",
  "/improbable.spatialos.playerauth.v2.PlayerAuthService/ListDevelopmentAuthenticationTokens",
  "/improbable.spatialos.playerauth.v2.PlayerAuthService/UpdateDevelopmentAuthenticationToken",
  "/improbable.spatialos.playerauth.v2.PlayerAuthService/ExpireDevelopmentAuthenticationToken",
  "/improbable.spatialos.playerauth.v2.PlayerAuthService/DeleteDevelopmentAuthenticationToken",
};

std::unique_ptr< PlayerAuthService::Stub> PlayerAuthService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PlayerAuthService::Stub> stub(new PlayerAuthService::Stub(channel));
  return stub;
}

PlayerAuthService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_CreateLoginToken_(PlayerAuthService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreatePlayerIdentityToken_(PlayerAuthService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DecodePlayerIdentityToken_(PlayerAuthService_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateDevelopmentAuthenticationToken_(PlayerAuthService_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetDevelopmentAuthenticationToken_(PlayerAuthService_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListDevelopmentAuthenticationTokens_(PlayerAuthService_method_names[5], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateDevelopmentAuthenticationToken_(PlayerAuthService_method_names[6], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ExpireDevelopmentAuthenticationToken_(PlayerAuthService_method_names[7], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteDevelopmentAuthenticationToken_(PlayerAuthService_method_names[8], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status PlayerAuthService::Stub::CreateLoginToken(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::CreateLoginTokenRequest& request, ::improbable::spatialos::playerauth::v2::CreateLoginTokenResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CreateLoginToken_, context, request, response);
}

void PlayerAuthService::Stub::experimental_async::CreateLoginToken(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::CreateLoginTokenRequest* request, ::improbable::spatialos::playerauth::v2::CreateLoginTokenResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreateLoginToken_, context, request, response, std::move(f));
}

void PlayerAuthService::Stub::experimental_async::CreateLoginToken(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::improbable::spatialos::playerauth::v2::CreateLoginTokenResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreateLoginToken_, context, request, response, std::move(f));
}

void PlayerAuthService::Stub::experimental_async::CreateLoginToken(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::CreateLoginTokenRequest* request, ::improbable::spatialos::playerauth::v2::CreateLoginTokenResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreateLoginToken_, context, request, response, reactor);
}

void PlayerAuthService::Stub::experimental_async::CreateLoginToken(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::improbable::spatialos::playerauth::v2::CreateLoginTokenResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreateLoginToken_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::improbable::spatialos::playerauth::v2::CreateLoginTokenResponse>* PlayerAuthService::Stub::AsyncCreateLoginTokenRaw(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::CreateLoginTokenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::improbable::spatialos::playerauth::v2::CreateLoginTokenResponse>::Create(channel_.get(), cq, rpcmethod_CreateLoginToken_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::improbable::spatialos::playerauth::v2::CreateLoginTokenResponse>* PlayerAuthService::Stub::PrepareAsyncCreateLoginTokenRaw(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::CreateLoginTokenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::improbable::spatialos::playerauth::v2::CreateLoginTokenResponse>::Create(channel_.get(), cq, rpcmethod_CreateLoginToken_, context, request, false);
}

::grpc::Status PlayerAuthService::Stub::CreatePlayerIdentityToken(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::CreatePlayerIdentityTokenRequest& request, ::improbable::spatialos::playerauth::v2::CreatePlayerIdentityTokenResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CreatePlayerIdentityToken_, context, request, response);
}

void PlayerAuthService::Stub::experimental_async::CreatePlayerIdentityToken(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::CreatePlayerIdentityTokenRequest* request, ::improbable::spatialos::playerauth::v2::CreatePlayerIdentityTokenResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreatePlayerIdentityToken_, context, request, response, std::move(f));
}

void PlayerAuthService::Stub::experimental_async::CreatePlayerIdentityToken(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::improbable::spatialos::playerauth::v2::CreatePlayerIdentityTokenResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreatePlayerIdentityToken_, context, request, response, std::move(f));
}

void PlayerAuthService::Stub::experimental_async::CreatePlayerIdentityToken(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::CreatePlayerIdentityTokenRequest* request, ::improbable::spatialos::playerauth::v2::CreatePlayerIdentityTokenResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreatePlayerIdentityToken_, context, request, response, reactor);
}

void PlayerAuthService::Stub::experimental_async::CreatePlayerIdentityToken(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::improbable::spatialos::playerauth::v2::CreatePlayerIdentityTokenResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreatePlayerIdentityToken_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::improbable::spatialos::playerauth::v2::CreatePlayerIdentityTokenResponse>* PlayerAuthService::Stub::AsyncCreatePlayerIdentityTokenRaw(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::CreatePlayerIdentityTokenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::improbable::spatialos::playerauth::v2::CreatePlayerIdentityTokenResponse>::Create(channel_.get(), cq, rpcmethod_CreatePlayerIdentityToken_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::improbable::spatialos::playerauth::v2::CreatePlayerIdentityTokenResponse>* PlayerAuthService::Stub::PrepareAsyncCreatePlayerIdentityTokenRaw(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::CreatePlayerIdentityTokenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::improbable::spatialos::playerauth::v2::CreatePlayerIdentityTokenResponse>::Create(channel_.get(), cq, rpcmethod_CreatePlayerIdentityToken_, context, request, false);
}

::grpc::Status PlayerAuthService::Stub::DecodePlayerIdentityToken(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::DecodePlayerIdentityTokenRequest& request, ::improbable::spatialos::playerauth::v2::DecodePlayerIdentityTokenResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_DecodePlayerIdentityToken_, context, request, response);
}

void PlayerAuthService::Stub::experimental_async::DecodePlayerIdentityToken(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::DecodePlayerIdentityTokenRequest* request, ::improbable::spatialos::playerauth::v2::DecodePlayerIdentityTokenResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_DecodePlayerIdentityToken_, context, request, response, std::move(f));
}

void PlayerAuthService::Stub::experimental_async::DecodePlayerIdentityToken(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::improbable::spatialos::playerauth::v2::DecodePlayerIdentityTokenResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_DecodePlayerIdentityToken_, context, request, response, std::move(f));
}

void PlayerAuthService::Stub::experimental_async::DecodePlayerIdentityToken(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::DecodePlayerIdentityTokenRequest* request, ::improbable::spatialos::playerauth::v2::DecodePlayerIdentityTokenResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_DecodePlayerIdentityToken_, context, request, response, reactor);
}

void PlayerAuthService::Stub::experimental_async::DecodePlayerIdentityToken(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::improbable::spatialos::playerauth::v2::DecodePlayerIdentityTokenResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_DecodePlayerIdentityToken_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::improbable::spatialos::playerauth::v2::DecodePlayerIdentityTokenResponse>* PlayerAuthService::Stub::AsyncDecodePlayerIdentityTokenRaw(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::DecodePlayerIdentityTokenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::improbable::spatialos::playerauth::v2::DecodePlayerIdentityTokenResponse>::Create(channel_.get(), cq, rpcmethod_DecodePlayerIdentityToken_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::improbable::spatialos::playerauth::v2::DecodePlayerIdentityTokenResponse>* PlayerAuthService::Stub::PrepareAsyncDecodePlayerIdentityTokenRaw(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::DecodePlayerIdentityTokenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::improbable::spatialos::playerauth::v2::DecodePlayerIdentityTokenResponse>::Create(channel_.get(), cq, rpcmethod_DecodePlayerIdentityToken_, context, request, false);
}

::grpc::Status PlayerAuthService::Stub::CreateDevelopmentAuthenticationToken(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::CreateDevelopmentAuthenticationTokenRequest& request, ::improbable::spatialos::playerauth::v2::CreateDevelopmentAuthenticationTokenResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CreateDevelopmentAuthenticationToken_, context, request, response);
}

void PlayerAuthService::Stub::experimental_async::CreateDevelopmentAuthenticationToken(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::CreateDevelopmentAuthenticationTokenRequest* request, ::improbable::spatialos::playerauth::v2::CreateDevelopmentAuthenticationTokenResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreateDevelopmentAuthenticationToken_, context, request, response, std::move(f));
}

void PlayerAuthService::Stub::experimental_async::CreateDevelopmentAuthenticationToken(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::improbable::spatialos::playerauth::v2::CreateDevelopmentAuthenticationTokenResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreateDevelopmentAuthenticationToken_, context, request, response, std::move(f));
}

void PlayerAuthService::Stub::experimental_async::CreateDevelopmentAuthenticationToken(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::CreateDevelopmentAuthenticationTokenRequest* request, ::improbable::spatialos::playerauth::v2::CreateDevelopmentAuthenticationTokenResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreateDevelopmentAuthenticationToken_, context, request, response, reactor);
}

void PlayerAuthService::Stub::experimental_async::CreateDevelopmentAuthenticationToken(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::improbable::spatialos::playerauth::v2::CreateDevelopmentAuthenticationTokenResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreateDevelopmentAuthenticationToken_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::improbable::spatialos::playerauth::v2::CreateDevelopmentAuthenticationTokenResponse>* PlayerAuthService::Stub::AsyncCreateDevelopmentAuthenticationTokenRaw(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::CreateDevelopmentAuthenticationTokenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::improbable::spatialos::playerauth::v2::CreateDevelopmentAuthenticationTokenResponse>::Create(channel_.get(), cq, rpcmethod_CreateDevelopmentAuthenticationToken_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::improbable::spatialos::playerauth::v2::CreateDevelopmentAuthenticationTokenResponse>* PlayerAuthService::Stub::PrepareAsyncCreateDevelopmentAuthenticationTokenRaw(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::CreateDevelopmentAuthenticationTokenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::improbable::spatialos::playerauth::v2::CreateDevelopmentAuthenticationTokenResponse>::Create(channel_.get(), cq, rpcmethod_CreateDevelopmentAuthenticationToken_, context, request, false);
}

::grpc::Status PlayerAuthService::Stub::GetDevelopmentAuthenticationToken(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::GetDevelopmentAuthenticationTokenRequest& request, ::improbable::spatialos::playerauth::v2::GetDevelopmentAuthenticationTokenResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetDevelopmentAuthenticationToken_, context, request, response);
}

void PlayerAuthService::Stub::experimental_async::GetDevelopmentAuthenticationToken(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::GetDevelopmentAuthenticationTokenRequest* request, ::improbable::spatialos::playerauth::v2::GetDevelopmentAuthenticationTokenResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetDevelopmentAuthenticationToken_, context, request, response, std::move(f));
}

void PlayerAuthService::Stub::experimental_async::GetDevelopmentAuthenticationToken(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::improbable::spatialos::playerauth::v2::GetDevelopmentAuthenticationTokenResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetDevelopmentAuthenticationToken_, context, request, response, std::move(f));
}

void PlayerAuthService::Stub::experimental_async::GetDevelopmentAuthenticationToken(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::GetDevelopmentAuthenticationTokenRequest* request, ::improbable::spatialos::playerauth::v2::GetDevelopmentAuthenticationTokenResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetDevelopmentAuthenticationToken_, context, request, response, reactor);
}

void PlayerAuthService::Stub::experimental_async::GetDevelopmentAuthenticationToken(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::improbable::spatialos::playerauth::v2::GetDevelopmentAuthenticationTokenResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetDevelopmentAuthenticationToken_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::improbable::spatialos::playerauth::v2::GetDevelopmentAuthenticationTokenResponse>* PlayerAuthService::Stub::AsyncGetDevelopmentAuthenticationTokenRaw(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::GetDevelopmentAuthenticationTokenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::improbable::spatialos::playerauth::v2::GetDevelopmentAuthenticationTokenResponse>::Create(channel_.get(), cq, rpcmethod_GetDevelopmentAuthenticationToken_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::improbable::spatialos::playerauth::v2::GetDevelopmentAuthenticationTokenResponse>* PlayerAuthService::Stub::PrepareAsyncGetDevelopmentAuthenticationTokenRaw(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::GetDevelopmentAuthenticationTokenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::improbable::spatialos::playerauth::v2::GetDevelopmentAuthenticationTokenResponse>::Create(channel_.get(), cq, rpcmethod_GetDevelopmentAuthenticationToken_, context, request, false);
}

::grpc::Status PlayerAuthService::Stub::ListDevelopmentAuthenticationTokens(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::ListDevelopmentAuthenticationTokensRequest& request, ::improbable::spatialos::playerauth::v2::ListDevelopmentAuthenticationTokensResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ListDevelopmentAuthenticationTokens_, context, request, response);
}

void PlayerAuthService::Stub::experimental_async::ListDevelopmentAuthenticationTokens(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::ListDevelopmentAuthenticationTokensRequest* request, ::improbable::spatialos::playerauth::v2::ListDevelopmentAuthenticationTokensResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ListDevelopmentAuthenticationTokens_, context, request, response, std::move(f));
}

void PlayerAuthService::Stub::experimental_async::ListDevelopmentAuthenticationTokens(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::improbable::spatialos::playerauth::v2::ListDevelopmentAuthenticationTokensResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ListDevelopmentAuthenticationTokens_, context, request, response, std::move(f));
}

void PlayerAuthService::Stub::experimental_async::ListDevelopmentAuthenticationTokens(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::ListDevelopmentAuthenticationTokensRequest* request, ::improbable::spatialos::playerauth::v2::ListDevelopmentAuthenticationTokensResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ListDevelopmentAuthenticationTokens_, context, request, response, reactor);
}

void PlayerAuthService::Stub::experimental_async::ListDevelopmentAuthenticationTokens(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::improbable::spatialos::playerauth::v2::ListDevelopmentAuthenticationTokensResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ListDevelopmentAuthenticationTokens_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::improbable::spatialos::playerauth::v2::ListDevelopmentAuthenticationTokensResponse>* PlayerAuthService::Stub::AsyncListDevelopmentAuthenticationTokensRaw(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::ListDevelopmentAuthenticationTokensRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::improbable::spatialos::playerauth::v2::ListDevelopmentAuthenticationTokensResponse>::Create(channel_.get(), cq, rpcmethod_ListDevelopmentAuthenticationTokens_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::improbable::spatialos::playerauth::v2::ListDevelopmentAuthenticationTokensResponse>* PlayerAuthService::Stub::PrepareAsyncListDevelopmentAuthenticationTokensRaw(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::ListDevelopmentAuthenticationTokensRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::improbable::spatialos::playerauth::v2::ListDevelopmentAuthenticationTokensResponse>::Create(channel_.get(), cq, rpcmethod_ListDevelopmentAuthenticationTokens_, context, request, false);
}

::grpc::Status PlayerAuthService::Stub::UpdateDevelopmentAuthenticationToken(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::UpdateDevelopmentAuthenticationTokenRequest& request, ::improbable::spatialos::playerauth::v2::UpdateDevelopmentAuthenticationTokenResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_UpdateDevelopmentAuthenticationToken_, context, request, response);
}

void PlayerAuthService::Stub::experimental_async::UpdateDevelopmentAuthenticationToken(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::UpdateDevelopmentAuthenticationTokenRequest* request, ::improbable::spatialos::playerauth::v2::UpdateDevelopmentAuthenticationTokenResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_UpdateDevelopmentAuthenticationToken_, context, request, response, std::move(f));
}

void PlayerAuthService::Stub::experimental_async::UpdateDevelopmentAuthenticationToken(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::improbable::spatialos::playerauth::v2::UpdateDevelopmentAuthenticationTokenResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_UpdateDevelopmentAuthenticationToken_, context, request, response, std::move(f));
}

void PlayerAuthService::Stub::experimental_async::UpdateDevelopmentAuthenticationToken(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::UpdateDevelopmentAuthenticationTokenRequest* request, ::improbable::spatialos::playerauth::v2::UpdateDevelopmentAuthenticationTokenResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_UpdateDevelopmentAuthenticationToken_, context, request, response, reactor);
}

void PlayerAuthService::Stub::experimental_async::UpdateDevelopmentAuthenticationToken(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::improbable::spatialos::playerauth::v2::UpdateDevelopmentAuthenticationTokenResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_UpdateDevelopmentAuthenticationToken_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::improbable::spatialos::playerauth::v2::UpdateDevelopmentAuthenticationTokenResponse>* PlayerAuthService::Stub::AsyncUpdateDevelopmentAuthenticationTokenRaw(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::UpdateDevelopmentAuthenticationTokenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::improbable::spatialos::playerauth::v2::UpdateDevelopmentAuthenticationTokenResponse>::Create(channel_.get(), cq, rpcmethod_UpdateDevelopmentAuthenticationToken_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::improbable::spatialos::playerauth::v2::UpdateDevelopmentAuthenticationTokenResponse>* PlayerAuthService::Stub::PrepareAsyncUpdateDevelopmentAuthenticationTokenRaw(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::UpdateDevelopmentAuthenticationTokenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::improbable::spatialos::playerauth::v2::UpdateDevelopmentAuthenticationTokenResponse>::Create(channel_.get(), cq, rpcmethod_UpdateDevelopmentAuthenticationToken_, context, request, false);
}

::grpc::Status PlayerAuthService::Stub::ExpireDevelopmentAuthenticationToken(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::ExpireDevelopmentAuthenticationTokenRequest& request, ::improbable::spatialos::playerauth::v2::ExpireDevelopmentAuthenticationTokenResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ExpireDevelopmentAuthenticationToken_, context, request, response);
}

void PlayerAuthService::Stub::experimental_async::ExpireDevelopmentAuthenticationToken(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::ExpireDevelopmentAuthenticationTokenRequest* request, ::improbable::spatialos::playerauth::v2::ExpireDevelopmentAuthenticationTokenResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ExpireDevelopmentAuthenticationToken_, context, request, response, std::move(f));
}

void PlayerAuthService::Stub::experimental_async::ExpireDevelopmentAuthenticationToken(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::improbable::spatialos::playerauth::v2::ExpireDevelopmentAuthenticationTokenResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ExpireDevelopmentAuthenticationToken_, context, request, response, std::move(f));
}

void PlayerAuthService::Stub::experimental_async::ExpireDevelopmentAuthenticationToken(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::ExpireDevelopmentAuthenticationTokenRequest* request, ::improbable::spatialos::playerauth::v2::ExpireDevelopmentAuthenticationTokenResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ExpireDevelopmentAuthenticationToken_, context, request, response, reactor);
}

void PlayerAuthService::Stub::experimental_async::ExpireDevelopmentAuthenticationToken(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::improbable::spatialos::playerauth::v2::ExpireDevelopmentAuthenticationTokenResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ExpireDevelopmentAuthenticationToken_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::improbable::spatialos::playerauth::v2::ExpireDevelopmentAuthenticationTokenResponse>* PlayerAuthService::Stub::AsyncExpireDevelopmentAuthenticationTokenRaw(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::ExpireDevelopmentAuthenticationTokenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::improbable::spatialos::playerauth::v2::ExpireDevelopmentAuthenticationTokenResponse>::Create(channel_.get(), cq, rpcmethod_ExpireDevelopmentAuthenticationToken_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::improbable::spatialos::playerauth::v2::ExpireDevelopmentAuthenticationTokenResponse>* PlayerAuthService::Stub::PrepareAsyncExpireDevelopmentAuthenticationTokenRaw(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::ExpireDevelopmentAuthenticationTokenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::improbable::spatialos::playerauth::v2::ExpireDevelopmentAuthenticationTokenResponse>::Create(channel_.get(), cq, rpcmethod_ExpireDevelopmentAuthenticationToken_, context, request, false);
}

::grpc::Status PlayerAuthService::Stub::DeleteDevelopmentAuthenticationToken(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::DeleteDevelopmentAuthenticationTokenRequest& request, ::improbable::spatialos::playerauth::v2::DeleteDevelopmentAuthenticationTokenResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_DeleteDevelopmentAuthenticationToken_, context, request, response);
}

void PlayerAuthService::Stub::experimental_async::DeleteDevelopmentAuthenticationToken(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::DeleteDevelopmentAuthenticationTokenRequest* request, ::improbable::spatialos::playerauth::v2::DeleteDevelopmentAuthenticationTokenResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_DeleteDevelopmentAuthenticationToken_, context, request, response, std::move(f));
}

void PlayerAuthService::Stub::experimental_async::DeleteDevelopmentAuthenticationToken(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::improbable::spatialos::playerauth::v2::DeleteDevelopmentAuthenticationTokenResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_DeleteDevelopmentAuthenticationToken_, context, request, response, std::move(f));
}

void PlayerAuthService::Stub::experimental_async::DeleteDevelopmentAuthenticationToken(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::DeleteDevelopmentAuthenticationTokenRequest* request, ::improbable::spatialos::playerauth::v2::DeleteDevelopmentAuthenticationTokenResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_DeleteDevelopmentAuthenticationToken_, context, request, response, reactor);
}

void PlayerAuthService::Stub::experimental_async::DeleteDevelopmentAuthenticationToken(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::improbable::spatialos::playerauth::v2::DeleteDevelopmentAuthenticationTokenResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_DeleteDevelopmentAuthenticationToken_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::improbable::spatialos::playerauth::v2::DeleteDevelopmentAuthenticationTokenResponse>* PlayerAuthService::Stub::AsyncDeleteDevelopmentAuthenticationTokenRaw(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::DeleteDevelopmentAuthenticationTokenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::improbable::spatialos::playerauth::v2::DeleteDevelopmentAuthenticationTokenResponse>::Create(channel_.get(), cq, rpcmethod_DeleteDevelopmentAuthenticationToken_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::improbable::spatialos::playerauth::v2::DeleteDevelopmentAuthenticationTokenResponse>* PlayerAuthService::Stub::PrepareAsyncDeleteDevelopmentAuthenticationTokenRaw(::grpc::ClientContext* context, const ::improbable::spatialos::playerauth::v2::DeleteDevelopmentAuthenticationTokenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::improbable::spatialos::playerauth::v2::DeleteDevelopmentAuthenticationTokenResponse>::Create(channel_.get(), cq, rpcmethod_DeleteDevelopmentAuthenticationToken_, context, request, false);
}

PlayerAuthService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PlayerAuthService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PlayerAuthService::Service, ::improbable::spatialos::playerauth::v2::CreateLoginTokenRequest, ::improbable::spatialos::playerauth::v2::CreateLoginTokenResponse>(
          std::mem_fn(&PlayerAuthService::Service::CreateLoginToken), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PlayerAuthService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PlayerAuthService::Service, ::improbable::spatialos::playerauth::v2::CreatePlayerIdentityTokenRequest, ::improbable::spatialos::playerauth::v2::CreatePlayerIdentityTokenResponse>(
          std::mem_fn(&PlayerAuthService::Service::CreatePlayerIdentityToken), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PlayerAuthService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PlayerAuthService::Service, ::improbable::spatialos::playerauth::v2::DecodePlayerIdentityTokenRequest, ::improbable::spatialos::playerauth::v2::DecodePlayerIdentityTokenResponse>(
          std::mem_fn(&PlayerAuthService::Service::DecodePlayerIdentityToken), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PlayerAuthService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PlayerAuthService::Service, ::improbable::spatialos::playerauth::v2::CreateDevelopmentAuthenticationTokenRequest, ::improbable::spatialos::playerauth::v2::CreateDevelopmentAuthenticationTokenResponse>(
          std::mem_fn(&PlayerAuthService::Service::CreateDevelopmentAuthenticationToken), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PlayerAuthService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PlayerAuthService::Service, ::improbable::spatialos::playerauth::v2::GetDevelopmentAuthenticationTokenRequest, ::improbable::spatialos::playerauth::v2::GetDevelopmentAuthenticationTokenResponse>(
          std::mem_fn(&PlayerAuthService::Service::GetDevelopmentAuthenticationToken), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PlayerAuthService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PlayerAuthService::Service, ::improbable::spatialos::playerauth::v2::ListDevelopmentAuthenticationTokensRequest, ::improbable::spatialos::playerauth::v2::ListDevelopmentAuthenticationTokensResponse>(
          std::mem_fn(&PlayerAuthService::Service::ListDevelopmentAuthenticationTokens), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PlayerAuthService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PlayerAuthService::Service, ::improbable::spatialos::playerauth::v2::UpdateDevelopmentAuthenticationTokenRequest, ::improbable::spatialos::playerauth::v2::UpdateDevelopmentAuthenticationTokenResponse>(
          std::mem_fn(&PlayerAuthService::Service::UpdateDevelopmentAuthenticationToken), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PlayerAuthService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PlayerAuthService::Service, ::improbable::spatialos::playerauth::v2::ExpireDevelopmentAuthenticationTokenRequest, ::improbable::spatialos::playerauth::v2::ExpireDevelopmentAuthenticationTokenResponse>(
          std::mem_fn(&PlayerAuthService::Service::ExpireDevelopmentAuthenticationToken), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PlayerAuthService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PlayerAuthService::Service, ::improbable::spatialos::playerauth::v2::DeleteDevelopmentAuthenticationTokenRequest, ::improbable::spatialos::playerauth::v2::DeleteDevelopmentAuthenticationTokenResponse>(
          std::mem_fn(&PlayerAuthService::Service::DeleteDevelopmentAuthenticationToken), this)));
}

PlayerAuthService::Service::~Service() {
}

::grpc::Status PlayerAuthService::Service::CreateLoginToken(::grpc::ServerContext* context, const ::improbable::spatialos::playerauth::v2::CreateLoginTokenRequest* request, ::improbable::spatialos::playerauth::v2::CreateLoginTokenResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PlayerAuthService::Service::CreatePlayerIdentityToken(::grpc::ServerContext* context, const ::improbable::spatialos::playerauth::v2::CreatePlayerIdentityTokenRequest* request, ::improbable::spatialos::playerauth::v2::CreatePlayerIdentityTokenResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PlayerAuthService::Service::DecodePlayerIdentityToken(::grpc::ServerContext* context, const ::improbable::spatialos::playerauth::v2::DecodePlayerIdentityTokenRequest* request, ::improbable::spatialos::playerauth::v2::DecodePlayerIdentityTokenResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PlayerAuthService::Service::CreateDevelopmentAuthenticationToken(::grpc::ServerContext* context, const ::improbable::spatialos::playerauth::v2::CreateDevelopmentAuthenticationTokenRequest* request, ::improbable::spatialos::playerauth::v2::CreateDevelopmentAuthenticationTokenResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PlayerAuthService::Service::GetDevelopmentAuthenticationToken(::grpc::ServerContext* context, const ::improbable::spatialos::playerauth::v2::GetDevelopmentAuthenticationTokenRequest* request, ::improbable::spatialos::playerauth::v2::GetDevelopmentAuthenticationTokenResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PlayerAuthService::Service::ListDevelopmentAuthenticationTokens(::grpc::ServerContext* context, const ::improbable::spatialos::playerauth::v2::ListDevelopmentAuthenticationTokensRequest* request, ::improbable::spatialos::playerauth::v2::ListDevelopmentAuthenticationTokensResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PlayerAuthService::Service::UpdateDevelopmentAuthenticationToken(::grpc::ServerContext* context, const ::improbable::spatialos::playerauth::v2::UpdateDevelopmentAuthenticationTokenRequest* request, ::improbable::spatialos::playerauth::v2::UpdateDevelopmentAuthenticationTokenResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PlayerAuthService::Service::ExpireDevelopmentAuthenticationToken(::grpc::ServerContext* context, const ::improbable::spatialos::playerauth::v2::ExpireDevelopmentAuthenticationTokenRequest* request, ::improbable::spatialos::playerauth::v2::ExpireDevelopmentAuthenticationTokenResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PlayerAuthService::Service::DeleteDevelopmentAuthenticationToken(::grpc::ServerContext* context, const ::improbable::spatialos::playerauth::v2::DeleteDevelopmentAuthenticationTokenRequest* request, ::improbable::spatialos::playerauth::v2::DeleteDevelopmentAuthenticationTokenResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace improbable
}  // namespace spatialos
}  // namespace playerauth
}  // namespace v2

