// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: github.com/improbable-io/go-proto-logfields/logfields.proto

#include "github.com/improbable-io/go-proto-logfields/logfields.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_LogField_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto;
namespace improbable {
class LogFieldDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<LogField> _instance;
} _LogField_default_instance_;
}  // namespace improbable
static void InitDefaultsscc_info_LogField_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::improbable::_LogField_default_instance_;
    new (ptr) ::improbable::LogField();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::improbable::LogField::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_LogField_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_LogField_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::improbable::LogField, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::improbable::LogField, name_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::improbable::LogField)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::improbable::_LogField_default_instance_),
};

const char descriptor_table_protodef_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n;github.com/improbable-io/go-proto-logf"
  "ields/logfields.proto\022\nimprobable\032 googl"
  "e/protobuf/descriptor.proto\"\030\n\010LogField\022"
  "\014\n\004name\030\001 \001(\t:G\n\010logfield\022\035.google.proto"
  "buf.FieldOptions\030\264\345\003 \001(\0132\024.improbable.Lo"
  "gFieldB\013Z\tlogfieldsb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto_sccs[1] = {
  &scc_info_LogField_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto = {
  false, false, descriptor_table_protodef_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto, "github.com/improbable-io/go-proto-logfields/logfields.proto", 227,
  &descriptor_table_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto_once, descriptor_table_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto_sccs, descriptor_table_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto::offsets,
  file_level_metadata_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto, 1, file_level_enum_descriptors_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto, file_level_service_descriptors_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto)), true);
namespace improbable {

// ===================================================================

void LogField::InitAsDefaultInstance() {
}
class LogField::_Internal {
 public:
};

LogField::LogField(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:improbable.LogField)
}
LogField::LogField(const LogField& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_name(),
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:improbable.LogField)
}

void LogField::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_LogField_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

LogField::~LogField() {
  // @@protoc_insertion_point(destructor:improbable.LogField)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void LogField::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void LogField::ArenaDtor(void* object) {
  LogField* _this = reinterpret_cast< LogField* >(object);
  (void)_this;
}
void LogField::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void LogField::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const LogField& LogField::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_LogField_github_2ecom_2fimprobable_2dio_2fgo_2dproto_2dlogfields_2flogfields_2eproto.base);
  return *internal_default_instance();
}


void LogField::Clear() {
// @@protoc_insertion_point(message_clear_start:improbable.LogField)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LogField::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "improbable.LogField.name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* LogField::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:improbable.LogField)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "improbable.LogField.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:improbable.LogField)
  return target;
}

size_t LogField::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:improbable.LogField)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LogField::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:improbable.LogField)
  GOOGLE_DCHECK_NE(&from, this);
  const LogField* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<LogField>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:improbable.LogField)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:improbable.LogField)
    MergeFrom(*source);
  }
}

void LogField::MergeFrom(const LogField& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:improbable.LogField)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {
    _internal_set_name(from._internal_name());
  }
}

void LogField::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:improbable.LogField)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LogField::CopyFrom(const LogField& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:improbable.LogField)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LogField::IsInitialized() const {
  return true;
}

void LogField::InternalSwap(LogField* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  name_.Swap(&other->name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata LogField::GetMetadata() const {
  return GetMetadataStatic();
}

::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::improbable::LogField >, 11, false >
  logfield(kLogfieldFieldNumber, ::improbable::LogField::default_instance());

// @@protoc_insertion_point(namespace_scope)
}  // namespace improbable
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::improbable::LogField* Arena::CreateMaybeMessage< ::improbable::LogField >(Arena* arena) {
  return Arena::CreateMessageInternal< ::improbable::LogField >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
